@HospitalManagementAPI_HostAddress = http://localhost:5286

### Obtener una lista de pronósticos del tiempo
GET {{HospitalManagementAPI_HostAddress}}/weatherforecast/
Accept: application/json

### Obtener información sobre un paciente específico
GET {{HospitalManagementAPI_HostAddress}}/api/patients/1
Accept: application/json

### Crear un nuevo paciente
POST {{HospitalManagementAPI_HostAddress}}/api/patients
Content-Type: application/json

{
  "id": 2,
  "firstName": "John",
  "lastName": "Doe",
  "birthDate": "1985-04-12T00:00:00",
  "address": "123 Main St",
  "phoneNumber": "555-1234"
}

### Actualizar información de un paciente
PUT {{HospitalManagementAPI_HostAddress}}/api/patients/1
Content-Type: application/json

{
  "id": 1,
  "firstName": "Jane",
  "lastName": "Doe",
  "birthDate": "1985-04-12T00:00:00",
  "address": "456 Elm St",
  "phoneNumber": "555-5678"
}

### Eliminar un paciente
DELETE {{HospitalManagementAPI_HostAddress}}/api/patients/1
